### Register/create user
POST https://microbloglite.herokuapp.com/api/users
Content-Type: application/json

{
    "username": "snk",
    "fullName": "Samuel Kahura",
    "password": "snk-99"
}

### Login
POST https://microbloglite.herokuapp.com/auth/login
Content-Type: application/json

{
    "username": "snk",
    "password": "snk-99"
}

### Get POSTS
GET https://microbloglite.herokuapp.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNuayIsImlhdCI6MTY3MDU5NTUxMywiZXhwIjoxNjcwNjgxOTEzfQ.UY21M8XBMVumv257Zr_gdqv6K9o3RCvle_2Kw00iQKc