### Register or create new user
GET https://microbloglite.herokuapp.com/api/users
Content-Type: application/json

{
    "username": "Suniverse",
    "fullName": "Steven Universe",
    "password": "l10nattack",
}

### Request login
Get https://microbloglite.herokuapp.com/api/login