### Register/create user
POST https://microbloglite.herokuapp.com/api/users
Content-Type: application/json

{
    "username": "snk",
    "fullName": "Samuel Kahura",
    "password": "snk-99"
}

### Login
POST https://microbloglite.herokuapp.com/auth/login
Content-Type: application/json

{
    "username": "snk",
    "password": "snk-99"
}

### Get Users
GET https://microbloglite.herokuapp.com/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNuayIsImlhdCI6MTY3MDQyNjc1MiwiZXhwIjoxNjcwNTEzMTUyfQ.e9MYltuKur_z3C6S5Yb5LXHiciOPSN8EW1Ga3rR-PSk
 
### Get Posts

GET https://microbloglite.herokuapp.com/api/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNuayIsImlhdCI6MTY3MDUxNDY1MywiZXhwIjoxNjcwNjAxMDUzfQ.D6j7YYiFe-umE00KxmHNjtgC8jndlxlcCTEjPX0zbxA
 
### Get Post

GET https://microbloglite.herokuapp.com/api/posts/6390c4873ba796f1da9ec7d6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNuayIsImlhdCI6MTY3MDQyNjc1MiwiZXhwIjoxNjcwNTEzMTUyfQ.e9MYltuKur_z3C6S5Yb5LXHiciOPSN8EW1Ga3rR-PSk
 